apiVersion: v2
name: medical-platform
description: GuMED - Medical Data Platform
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: "15.5.0"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: metabase
    version: "2.27.4"
    repository: https://pmint93.github.io/helm-charts
    condition: metabase.enabled
