global:
  postgresql:
    auth:
      postgresPassword: "postgres123"
      username: "medicaluser"
      password: "medical123"
      database: "medicaldb"


postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: "16.3.0-debian-12-r10"
    pullPolicy: IfNotPresent
  primary:
    persistence:
      enabled: true
      size: 1Gi

metabase:
  enabled: true
  auth:
    username: "admin@medical.local"
    password: "Metabase123!"

backend:
  replicaCount: 1
  image:
    repository: docker.io/library/medical-platform-backend
    tag: "latest"
    pullPolicy: IfNotPresent

dataLoader:
  image:
    repository: docker.io/library/medical-platform-data-loader
    tag: "latest"
    pullPolicy: IfNotPresent

ingress:
  enabled: false
  className: "nginx"
  hosts:
    - host: api.medical.local
      paths:
        - path: /
          pathType: Prefix
          service: backend
    - host: metabase.medical.local
      paths:
        - path: /
          pathType: Prefix
          service: metabase
